basic:
    name: 'SDSS User Guide'
    environments:
        production: 'https://sdssuserguide.stanford.edu/'
        staging: 'https://sdssuserguide-test.stanford.edu/'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - build
        - build/how-log
        - build/creating-content
        - build/paragraphs
        - build/paragraphs/banner
        - events/example-event
        - news/example-news
        - people/example-person
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 0
    scroll: false
    headers:
        - { value: '', header: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { type: title, selector: '' }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
